name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: |
        az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        docker build -t text-summarizer .
        docker tag text-summarizer ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/text-summarizer:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/text-summarizer:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: SSH into Azure VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: azureuser
        key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
        script: |
          az acr login --name ${{ secrets.AZURE_CONTAINER_REGISTRY }}
          docker pull ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/text-summarizer:latest
          docker stop $(docker ps -q --filter ancestor=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/text-summarizer:latest)
          docker rm $(docker ps -q --filter ancestor=${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/text-summarizer:latest)
          docker run -d -p 80:8080 ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io/text-summarizer:latest
